In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, date, time
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('train.csv', 
            index_col='id')


In [4]:
df.head()

vendor_id      pickup_datetime     dropoff_datetime  \
id                                                               
id2875421          2  2016-03-14 17:24:55  2016-03-14 17:32:30   
id2377394          1  2016-06-12 00:43:35  2016-06-12 00:54:38   
id3858529          2  2016-01-19 11:35:24  2016-01-19 12:10:48   
id3504673          2  2016-04-06 19:32:31  2016-04-06 19:39:40   
id2181028          2  2016-03-26 13:30:55  2016-03-26 13:38:10   

           passenger_count  pickup_longitude  pickup_latitude  \
id                                                              
id2875421                1        -73.982155        40.767937   
id2377394                1        -73.980415        40.738564   
id3858529                1        -73.979027        40.763939   
id3504673                1        -74.010040        40.719971   
id2181028                1        -73.973053        40.793209   

           dropoff_longitude  dropoff_latitude store_and_fwd_flag  \
id                                                                  
id2875421         -73.964630         40.765602                  N   
id2377394         -73.999481         40.731152                  N   
id3858529         -74.005333         40.710087                  N   
id3504673         -74.012268         40.706718                  N   
id2181028         -73.972923         40.782520                  N   

           trip_duration  
id                        
id2875421            455  
id2377394            663  
id3858529           2124  
id3504673            429  
id2181028            435

In [5]:
pickup_datetime = df.values


In [6]:
df.index


Index(['id2875421', 'id2377394', 'id3858529', 'id3504673', 'id2181028',
       'id0801584', 'id1813257', 'id1324603', 'id1301050', 'id0012891',
       ...
       'id3445276', 'id3027038', 'id0405770', 'id1920898', 'id1454193',
       'id2376096', 'id1049543', 'id2304944', 'id2714485', 'id1209952'],
      dtype='object', name='id', length=1458644)

In [7]:
pickuptimes  = df.loc[:, lambda df: ['pickup_datetime']]
pickuptimes = pickuptimes.values

In [8]:
pickuptimes



array([['2016-03-14 17:24:55'],
       ['2016-06-12 00:43:35'],
       ['2016-01-19 11:35:24'],
       ...,
       ['2016-04-22 06:57:41'],
       ['2016-01-05 15:56:26'],
       ['2016-04-05 14:44:25']], dtype=object)

In [9]:
a = pickuptimes[0]
a =a[0]

In [10]:

datetime_object = datetime.strptime(a, '%Y-%m-%d %H:%M:%S')

In [11]:
datetime_object

datetime.datetime(2016, 3, 14, 17, 24, 55)

In [12]:
datetime_object.year

2016

In [13]:
type(datetime_object)

datetime.datetime

In [36]:
datetime_list = [0] * pickuptimes.shape[0]
for i in range(pickuptimes.shape[0]):
    datetime_list[i] =  datetime.strptime(pickuptimes[i][0], '%Y-%m-%d %H:%M:%S')



In [45]:
print(datetime_list[1].year)

2016


In [59]:
time_mat = np.arange(pickuptimes.shape[0] * 4).reshape(pickuptimes.shape[0], 4)
print(time_mat)

[[      0       1       2       3]
 [      4       5       6       7]
 [      8       9      10      11]
 ...
 [5834564 5834565 5834566 5834567]
 [5834568 5834569 5834570 5834571]
 [5834572 5834573 5834574 5834575]]


In [72]:

for i in range(pickuptimes.shape[0]):
    time_mat[i,0] = datetime_list[i].month
    time_mat[i,1] = datetime_list[i].day
    time_mat[i,2] = datetime_list[i].hour
    time_mat[i,2] = str(datetime_list[0].year) + '/' + str(datetime_list[0].month) + '/' + str(datetime_list[0].day) + '/' + str(datetime_list[0].hour)
    
    

ValueError: invalid literal for int() with base 10: '2016/3/14/17'

In [55]:
print(time_mat)

[[ 3 14 17]
 [ 6 12  0]
 [ 1 19 11]
 ...
 [ 4 22  6]
 [ 1  5 15]
 [ 4  5 14]]


In [57]:
np.savetxt("time_mat.csv", time_mat, delimiter=",")

In [73]:

str(datetime_list[0].year) + '/' + str(datetime_list[0].month) + '/' + str(datetime_list[0].day) + '/' + str(datetime_list[0].hour)

'2016/3/14/17'

In [82]:
time_list =  []
for i in range(pickuptimes.shape[0]):
    time_list.append(str(datetime_list[0].year) + '/' + str(datetime_list[0].month) + '/' + str(datetime_list[0].day) + '/' + str(datetime_list[0].hour))
    
    

In [83]:
time_list

['2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17',
 '2016/3/14/17

In [84]:
import csv

with open('time_list', 'wb') as myfile:
    wr = csv.writer(time_list, quoting=csv.QUOTE_ALL)
    wr.writerow(time_list)

TypeError: argument 1 must have a "write" method